### PR TITLE
Initializated and Dockerized  model

### PR DESCRIPTION
**Pull request by samuelmaina**
@GemmaTuron , I was not able to solve the the model being created with  a docker image issue when using the --repo_path and not being able to download some packages. I had raised this issue   at https://github.com/ersilia-os/eos59rr/issues/1#issue-1793812725.
Used codespaces to put the model code and testing. Was able to fetch successfully and  preedict with the eml_dataset. 
   - [eos59rr_cli_fetch.log](https://github.com/ersilia-os/eos59rr/files/11994672/eos59rr_cli_fetch.log)
   - [eos59rr_eml_cli_predc.csv](https://github.com/ersilia-os/eos59rr/files/11994677/eos59rr_eml_cli_predc.csv)

### CODE REVIEW

**Comment by GemmaTuron** [comment]
@samuelmaina 
Please revise the dockerfile
you are pointing to the eos6m4j repo instead of this one:
`RUN wget https://raw.githubusercontent.com/ersilia-os/eos6m4j/main/model/framework/code/bidd-molmap/requirements.txt`

**Comment by samuelmaina** [comment]
@GemmaTuron , I guess the  PR must be be made first since this model has only the boilerplate code hence ` https://raw.githubusercontent.com/ersilia-os/os59rr/main/model/framework/code/bidd-molmap/requirements.txt `  wont exist. I will change the path later when the artifacts are uploaded to this model.

**Comment by GemmaTuron** [comment]
Add the changes in the PR and I'll merge even if the first check fails

**Comment by samuelmaina** [comment]
@GemmaTuron , Added . Test on PR is running

**Comment by GemmaTuron** [comment]
@samuelmaina 

Even when merged the tests are failing, please can you check?

**Pull request merged**
